name: Deploy to Github Pages
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persists-credentials: false

      - name: Install and Build
        run: |
          npm install
          npm run build
          git add dist
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git commit -m 'deploy'

      - name: Git Info
        run: |
          ls -halt
          git status

      - name: Deploy
        run: |
          git subtree push --prefix dist origin gh-pages

      # - name: Deploy
      #   uses: JameIves/github-pages-deploy-action@release/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     BRANCH: gh-pages
      #     folder: .
